### ISSUE TITLE
Doesn't work with hubot 2.4.7

### ISSUE THREAD

**Issue by morgoth** [nandub/hubot-irc#71]
I tried to use newest hubot, but it fails:

```
wojtek@ibm:~/Projects/hackerspace-hubot$ HUBOT_IRC_SERVER="irc.freenode.net" HUBOT_IRC_NICK="hubot_test_2331" HUBOT_IRC_ROOMS="#hubot-irc" bin/hubot -a irc
[Sat Mar 09 2013 23:36:03 GMT+0100 (CET)] ERROR Cannot load adapter irc - Error: Cannot find module 'hubot'
TypeError: Cannot call method 'on' of null
    at Object.<anonymous> (/home/wojtek/Projects/hackerspace-hubot/bin/hubot:136:19)
    at Object.<anonymous> (/home/wojtek/Projects/hackerspace-hubot/bin/hubot:140:4)
    at Module._compile (module.js:449:26)
    at Object.exports.run (/home/wojtek/.nvm/v0.8.22/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:124:25)
    at compileScript (/home/wojtek/.nvm/v0.8.22/lib/node_modules/coffee-script/lib/coffee-script/command.js:166:29)
    at fs.stat.notSources.(anonymous function) (/home/wojtek/.nvm/v0.8.22/lib/node_modules/coffee-script/lib/coffee-script/command.js:141:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

```
wojtek@ibm:~$ node -v
v0.8.22
```
